# Generated by Django 5.0.4 on 2024-04-20 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='producto_adquirido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.producto', verbose_name='producto'),
        ),
    ]
